name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Firefox Setup 84.0"
  comment: "Firefox Setup 84.0"
  url: "http://oyrenci-sesi.info/leech/files/ALGCAO.mp4"
  file_name: "Firefox Setup 84.0.exe"
  piece_size: 19 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
